- name: Update package cache
  apt:
    update_cache: yes

- name: Ensure Node.js and npm are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm

- name: Copy hostsfile
  copy:
    src: /etc/hosts
    dest: /etc/hosts

- name: Copy application folder
  copy:
    src: app/backend/
    dest: "{{ node_app_path }}"
    mode: "0755"

- name: Install Node.js dependencies
  npm:
    path: "{{ node_app_path }}"
    state: latest

- name: Populate db
  command: "/usr/bin/node {{ node_app_path }}/seeds.js"
  environment:
    DB_HOST: "{{ db_host }}"
    DB_USER: "{{ db_user }}"
    DB_PASS: "{{ db_pass }}"
    DB_NAME: "{{ db_name }}"
    PORT: "3000"
  args:
    chdir: "{{ node_app_path }}"
  when: populate_backend | default(false)

- name: Create systemd service file for the Node.js application
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Start and enable the Node.js application service
  systemd:
    name: app
    state: started
    enabled: yes
