version: '3.8'
services:
  paperclip:
    image: ghcr.io/paperclipai/paperclip:latest
    container_name: $PAPERCLIP_SERVICE_NAME
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
      - PAPERCLIP_HOME=/paperclip
      - PAPERCLIP_DEPLOYMENT_MODE=authenticated
      - PAPERCLIP_DEPLOYMENT_EXPOSURE=public
      - PAPERCLIP_AUTH_BASE_URL_MODE=explicit
      - PAPERCLIP_API_URL=$PAPERCLIP_LOCAL_URL
      - PAPERCLIP_PUBLIC_URL=$PAPERCLIP_PUBLIC_URL
      - PAPERCLIP_AUTH_PUBLIC_BASE_URL=$PAPERCLIP_PUBLIC_URL
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: volume
        source: paperclip
        target: /paperclip
        volume:
          nocopy: true   
    networks:
      - ia_apps  
    ports:
      - 3100:3100
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: $OPENWEBUI_SERVICE_NAME
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: volume
        source: open-webui
        target: /app/backend/data
        volume:
          nocopy: true   
    networks:
      - ia_apps
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart:  unless-stopped

networks:
  ia_apps:
    name: ia_apps
    ipam:
      driver: default
      config:
        - subnet: $IA_APPS_SUBNET
          gateway: $IA_APPS_GW

volumes:
  paperclip:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/paperclip/"

  open-webui:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/open-webui/"

