version: '3.8'
services:


networks:
  ia_apps:
    name: ia_apps
    ipam:
      driver: default
      config:
        - subnet: $IA_APPS_SUBNET
          gateway: $IA_APPS_GW

volumes:
