version: "3.2"
services:
  mysql:
    image: mariadb:latest
    container_name: $MARIADB_SERVICE_NAME
    ports:
    - 3306:3306
    labels:
      - com.centurylinklabs.watchtower.monitor-only="true"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: volume
        source: mysql
        target: /var/lib/mysql
        volume:
          nocopy: true  
    networks:
      - internalapps
    restart: always

  pgsql:
    image: postgres:15
    container_name: $PGDB_SERVICE_NAME
    environment:
    - POSTGRES_USER=$PGBD_USER
    - POSTGRES_PASSWORD=$PGBD_PASSWORD
    - POSTGRES_DB=$PGBD_DB
    - PGDATA=/var/lib/postgresql/data/pgdata
    labels:
      - com.centurylinklabs.watchtower.monitor-only="true"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: volume
        source: pgsql
        target: /var/lib/postgresql/data/pgdata
        volume:
          nocopy: true  
    networks:
      - internalapps
    restart: always          

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: $PMA_SERVICE_NAME
    ports: 
    - 8881:80
    depends_on:
    - $MARIADB_SERVICE_NAME    
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - PMA_ARBITRARY=1
#    labels:
#    - traefik.enable=true 
#    - traefik.http.routers.$PMA_SERVICE_NAME.rule=Host(`$PMA_ADDR_NAME.$DOMAIN`)
#    - traefik.http.routers.$PMA_SERVICE_NAME.entrypoints=web
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.rule=Host(`$PMA_ADDR_NAME.$DOMAIN`)
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.entrypoints=webs
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.middlewares=$AUTHELIA_SERVICE_NAME@docker
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.tls=true
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.service=$PMA_SERVICE_NAME
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.tls.certresolver=$CERTRESOLVER
#    - traefik.http.services.$PMA_SERVICE_NAME.loadbalancer.server.port=8978
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: volume
        source: phpmyadmin
        target: /config
        volume:
          nocopy: true  
    restart: always  
    networks:
      - internalapps

  phppgadmin:
    image: dpage/pgadmin4:latest
    container_name: $PGA_SERVICE_NAME
    ports: 
    - 8887:80
    depends_on:
    - $PGDB_SERVICE_NAME    
    environment:
    - PGADMIN_DEFAULT_EMAIL=$PGA_DEFAULT_EMAIL
    - PGADMIN_DEFAULT_PASSWORD=$PGA_DEFAULT_PASSWORD
#    labels:
#    - traefik.enable=true 
#    - traefik.http.routers.$PMA_SERVICE_NAME.rule=Host(`$PMA_ADDR_NAME.$DOMAIN`)
#    - traefik.http.routers.$PMA_SERVICE_NAME.entrypoints=web
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.rule=Host(`$PMA_ADDR_NAME.$DOMAIN`)
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.entrypoints=webs
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.middlewares=$AUTHELIA_SERVICE_NAME@docker
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.tls=true
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.service=$PMA_SERVICE_NAME
#    - traefik.http.routers.$PMA_SERVICE_NAME-https.tls.certresolver=$CERTRESOLVER
#    - traefik.http.services.$PMA_SERVICE_NAME.loadbalancer.server.port=8978
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: volume
        source: phppgadmin
        target: /var/lib/pgadmin
        volume:
          nocopy: true  
    restart: always  
    networks:
      - internalapps

  zabbix-daemon:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: $ZABBIX_SERVER_SERVICE_NAME
    depends_on:
    - $PGDB_SERVICE_NAME
    ports:
    - 10456:10051
    environment:
    - DB_SERVER_HOST=$PGDB_SERVICE_NAME
    - POSTGRES_USER=$ZABBIX_PGSQL_USER
    - POSTGRES_PASSWORD=$ZABBIX_PGSQL_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: volume
        source: zabbix-modules
        target: /var/lib/zabbix/modules
        volume:
          nocopy: true  
    restart: always
    networks:
      - internalapps

  zabbix:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: $ZABBIX_SERVICE_NAME
    depends_on:
    - $ZABBIX_SERVER_SERVICE_NAME   
    ports:
    - 8888:8080
    environment:
    - DB_SERVER_HOST=$PGDB_SERVICE_NAME
    - POSTGRES_USER=$ZABBIX_PGSQL_USER
    - POSTGRES_PASSWORD=$ZABBIX_PGSQL_PASSWORD
    - ZBX_SERVER_HOST=$ZABBIX_SERVER_SERVICE_NAME
    - PHP_TZ=$TZ
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    restart: always
    networks:
      - internalapps

  guacamole-daemon:
    image: guacamole/guacd
    container_name: $GUACAMOLE_DAEMON_SERVICE_NAME
    depends_on:
    - $MARIADB_SERVICE_NAME   
    networks:
        - internalapps
    restart: always

  guacamole:
    image: guacamole/guacamole
    container_name: $GUACAMOLE_SERVICE_NAME
    depends_on:
    - $GUACAMOLE_DAEMON_SERVICE_NAME   
    environment:
      - MYSQL_DATABASE=$GUACAMOLE_MYSQL_DATABASE
      - MYSQL_USER=$GUACAMOLE_MYSQL_USER
      - MYSQL_PASSWORD=$GUACAMOLE_MYSQL_PASSWORD
      - MYSQL_HOSTNAME=$MARIADB_SERVICE_NAME
      - GUACD_HOSTNAME=$GUACAMOLE_DAEMON_SERVICE_NAME
    ports:
    - 8882:8080
#    labels:
#      - traefik.enable=true 
#      - traefik.http.routers.$GUACAMOLE_SERVICE_NAME.rule=Host(`$GUACAMOLE_ADDR_NAME.$DOMAIN`)
#      - traefik.http.routers.$GUACAMOLE_SERVICE_NAME.entrypoints=web
#      - traefik.http.routers.$GUACAMOLE_SERVICE_NAME-https.rule=Host(`$GUACAMOLE_ADDR_NAME.$DOMAIN`)
#      - traefik.http.routers.$GUACAMOLE_SERVICE_NAME-https.entrypoints=webs
#      - traefik.http.routers.$GUACAMOLE_SERVICE_NAME-https.middlewares=$AUTHELIA_SERVICE_NAME@docker
#      - traefik.http.routers.$GUACAMOLE_SERVICE_NAME-https.middlewares=$GUACAMOLE_SERVICE_NAME-prefix
#      - traefik.http.routers.$GUACAMOLE_SERVICE_NAME-https.tls=true
#      - traefik.http.routers.$GUACAMOLE_SERVICE_NAME-https.service=$GUACAMOLE_SERVICE_NAME
#      - traefik.http.routers.$GUACAMOLE_SERVICE_NAME-https.tls.certresolver=$CERTRESOLVER
#      - traefik.http.services.$GUACAMOLE_SERVICE_NAME.loadbalancer.server.port=8080
#      - traefik.http.middlewares.$GUACAMOLE_SERVICE_NAME-prefix.addprefix.prefix=/guacamole
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    networks:
    - internalapps
    restart: always

  shlink-daemon:
    image: shlinkio/shlink:stable
    container_name: $SHLINK_DAEMON_SERVICE_NAME
    depends_on:
    - $MARIADB_SERVICE_NAME   
    environment:
    - DEFAULT_DOMAIN=$SHLINK_DAEMON_ADDR_NAME.$DOMAIN_FORMAL
    - IS_HTTPS_ENABLED=true
    - GEOLITE_LICENSE_KEY=$SHLINK_DAEMON_GEOLITE_LICENSE_KEY
    - DB_DRIVER=$SHLINK_DAEMON_DB_DRIVER
    - DB_USER=$SHLINK_DAEMON_DB_USER
    - DB_PASSWORD=$SHLINK_DAEMON_DB_PASSWORD
    - DB_HOST=$MARIADB_SERVICE_NAME
    ports:
    - 8883:8080
#    labels:
#      - traefik.enable=true 
#      - traefik.http.routers.$SHLINK_DAEMON_SERVICE_NAME.rule=Host(`$SHLINK_DAEMON_ADDR_NAME.$DOMAIN_FORMAL`)
#      - traefik.http.routers.$SHLINK_DAEMON_SERVICE_NAME.entrypoints=web
#      - traefik.http.routers.$SHLINK_DAEMON_SERVICE_NAME-https.rule=Host(`$SHLINK_DAEMON_ADDR_NAME.$DOMAIN_FORMAL`)
#      - traefik.http.routers.$SHLINK_DAEMON_SERVICE_NAME-https.entrypoints=webs
#      - traefik.http.routers.$SHLINK_DAEMON_SERVICE_NAME-https.tls=true
#      - traefik.http.routers.$SHLINK_DAEMON_SERVICE_NAME-https.service=$SHLINK_DAEMON_SERVICE_NAME
#      - traefik.http.routers.$SHLINK_DAEMON_SERVICE_NAME-https.tls.certresolver=$CERTRESOLVER
#      - traefik.http.services.$SHLINK_DAEMON_SERVICE_NAME.loadbalancer.server.port=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    networks:
      - internalapps    
    
  shlink:
    image: shlinkio/shlink-web-client
    container_name: $SHLINK_SERVICE_NAME
    depends_on:
    - $SHLINK_DAEMON_SERVICE_NAME   
    environment:
    - SHLINK_SERVER_URL=https://$SHLINK_DAEMON_ADDR_NAME.$DOMAIN_FORMAL
    - SHLINK_SERVER_API_KEY=$SHLINK_DAEMON_API_KEY
    ports:
    - 8884:80
#    labels:
#      - traefik.enable=true 
#      - traefik.http.routers.$SHLINK_SERVICE_NAME.rule=Host(`$SHLINK_ADDR_NAME.$DOMAIN`)
#      - traefik.http.routers.$SHLINK_SERVICE_NAME.entrypoints=web
#      - traefik.http.routers.$SHLINK_SERVICE_NAME-https.rule=Host(`$SHLINK_ADDR_NAME.$DOMAIN`)
#      - traefik.http.routers.$SHLINK_SERVICE_NAME-https.entrypoints=webs
#      - traefik.http.routers.$SHLINK_SERVICE_NAME-https.middlewares=$AUTHELIA_SERVICE_NAME@docker
#      - traefik.http.routers.$SHLINK_SERVICE_NAME-https.tls=true
#      - traefik.http.routers.$SHLINK_SERVICE_NAME-https.service=$SHLINK_SERVICE_NAME
#      - traefik.http.routers.$SHLINK_SERVICE_NAME-https.tls.certresolver=$CERTRESOLVER
#      - traefik.http.services.$SHLINK_SERVICE_NAME.loadbalancer.server.port=80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: volume
        source: shlink
        target: /usr/share/nginx/html/conf.d/
        volume:
          nocopy: true  
    restart: always
    networks:
      - internalapps

  littlelink:
    image: timothystewart6/littlelink-server:latest
    container_name: $LITTLELINK_SERVICE_NAME
    environment:
      - META_TITLE=$LITTLELINK_META_TITLE
      - META_DESCRIPTION=$LITTLELINK_META_DESCRIPTION
      - META_AUTHOR=$LITTLELINK_META_AUTHOR
      - LANG=$LITTLELINK_LANG
      - META_INDEX_STATUS=$LITTLELINK_META_INDEX_STATUS
      - OG_SITE_NAME=$LITTLELINK_OG_SITE_NAME
      - OG_TITLE=$LITTLELINK_OG_TITLE
#      - OG_DESCRIPTION=
#      - OG_URL=https://
      - OG_IMAGE=$LITTLELINK_OG_IMAGE
      - OG_IMAGE_WIDTH=$LITTLELINK_OG_IMAGE_WIDTH
      - OG_IMAGE_HEIGHT=$LITTLELINK_OG_IMAGE_HEIGHT
#     - GA_TRACKING_ID=G-XXXXXXXXXX
      - THEME=$LITTLELINK_THEME
      - FAVICON_URL=$LITTLELINK_FAVICON_URL
      - AVATAR_URL=$LITTLELINK_AVATAR_URL
      - AVATAR_2X_URL=$LITTLELINK_AVATAR_2X_URL
      - AVATAR_ALT=$LITTLELINK_AVATAR_ALT
      - NAME=$LITTLELINK_NAME
      - BIO=$LITTLELINK_BIO
      # use ENV variable names for order, listed buttons will be boosted to the top
      - BUTTON_ORDER=$LITTLELINK_BUTTON_ORDER
      - CUSTOM_BUTTON_TEXT=$LITTLELINK_CUSTOM_BUTTON_TEXT
      - CUSTOM_BUTTON_URL=$LITTLELINK_CUSTOM_BUTTON_URL
      - CUSTOM_BUTTON_COLOR=$LITTLELINK_CUSTOM_BUTTON_COLOR
      - CUSTOM_BUTTON_TEXT_COLOR=$LITTLELINK_CUSTOM_BUTTON_TEXT_COLOR
      - CUSTOM_BUTTON_ALT_TEXT=$LITTLELINK_CUSTOM_BUTTON_ALT_TEXT
      - CUSTOM_BUTTON_NAME=$LITTLELINK_CUSTOM_BUTTON_NAME
      - CUSTOM_BUTTON_ICON=$LITTLELINK_CUSTOM_BUTTON_ICON
      - LINKED_IN=$LITTLELINK_LINKED_IN
      - GITHUB=$LITTLELINK_GITHUB
      - EMAIL=$LITTLELINK_EMAIL
      - FOOTER=$LITTLELINK_FOOTER
    ports:
    - 8885:3000
#    labels:
#      - traefik.enable=true 
#      - traefik.http.routers.$LITTLELINK_SERVICE_NAME.rule=Host(`$DOMAIN_FORMAL`, `www.$DOMAIN_FORMAL`, `$LITTLELINK_ADDR_NAME.$DOMAIN_FORMAL`)
#      - traefik.http.routers.$LITTLELINK_SERVICE_NAME.entrypoints=web
#      - traefik.http.routers.$LITTLELINK_SERVICE_NAME-https.rule=Host(`$DOMAIN_FORMAL`, `www.$DOMAIN_FORMAL`, `$LITTLELINK_ADDR_NAME.$DOMAIN_FORMAL`)
#      - traefik.http.routers.$LITTLELINK_SERVICE_NAME-https.entrypoints=webs
#      - traefik.http.routers.$LITTLELINK_SERVICE_NAME-https.middlewares=$LITTLELINK_SERVICE_NAME-apexredirect@docker
#      - traefik.http.routers.$LITTLELINK_SERVICE_NAME-https.tls=true
#      - traefik.http.routers.$LITTLELINK_SERVICE_NAME-https.tls.certresolver=$CERTRESOLVER
#      - traefik.http.routers.$LITTLELINK_SERVICE_NAME-https.service=$LITTLELINK_SERVICE_NAME
#      - traefik.http.middlewares.$LITTLELINK_SERVICE_NAME-apexredirect.redirectRegex.regex=^https:\/\/(?:www\.)?$DOMAIN_FORMAL/(.*)
#      - traefik.http.middlewares.$LITTLELINK_SERVICE_NAME-apexredirect.redirectRegex.replacement=https://$LITTLELINK_ADDR_NAME.$DOMAIN_FORMAL/$${1}
#      - traefik.http.middlewares.$LITTLELINK_SERVICE_NAME-apexredirect.redirectRegex.permanent=true
#      - traefik.http.services.$LITTLELINK_SERVICE_NAME.loadbalancer.server.port=3000
    restart: always
    networks:
      - internalapps
    security_opt:
      - no-new-privileges:true

  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    container_name: $PRIVATEBIN_SERVICE_NAME
    environment:
      - TZ=$TZ
    ports:
    - 8886:8080
#    labels:
#      - traefik.enable=true 
#      - traefik.http.routers.$PRIVATEBIN_SERVICE_NAME.rule=Host(`$PRIVATEBIN_ADDR_NAME.$DOMAIN`)
#      - traefik.http.routers.$PRIVATEBIN_SERVICE_NAME.entrypoints=web
#      - traefik.http.routers.$PRIVATEBIN_SERVICE_NAME-https.rule=Host(`$PRIVATEBIN_ADDR_NAME.$DOMAIN`)
#      - traefik.http.routers.$PRIVATEBIN_SERVICE_NAME-https.entrypoints=webs
#      - traefik.http.routers.$PRIVATEBIN_SERVICE_NAME-https.tls=true
#      - traefik.http.routers.$PRIVATEBIN_SERVICE_NAME-https.service=$PRIVATEBIN_SERVICE_NAME
#      - traefik.http.routers.$PRIVATEBIN_SERVICE_NAME-https.tls.certresolver=$CERTRESOLVER
#      - traefik.http.services.$PRIVATEBIN_SERVICE_NAME.loadbalancer.server.port=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/docker/ymls/privatebin.php:/srv/cfg/conf.php:ro
      - type: volume
        source: privatebin
        target: /srv/data
        volume: 
          nocopy: true  
    
    networks:
      - internalapps  
    restart: always

networks:
  internalapps:
    name: internalapps
    ipam:
      driver: default
      config:
        - subnet: $INTERNALAPPS_SUBNET
          gateway: $INTERNALAPPS_GW

volumes:
  shlink:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/shlink/"

  mysql:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/mysql/"

  pgsql:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/pgsql/"

  mongo:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/mongo/"

  privatebin:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/privatebin/"
  
  phpmyadmin:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/phpmyadmin/"
  
  phppgadmin:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/phppgadmin/"

  zabbix-modules:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/zabbix/modules/"