version: "3.2"
services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:latest
    container_name: $ZABBIX_PROXY_SERVICE_NAME
    environment:
    - ZBX_SERVER_HOST=$ZABBIX_SERVER_SERVICE_NAME
    - ZBX_HOSTNAME=$ZABBIX_PROXY_SERVICE_NAME
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    networks:
      - apps
    ports:
    - 10456:10051
    restart: unless-stopped

  minecraft:
    image: itzg/minecraft-bedrock-server:latest
    container_name: $MINECRAFT_SERVICE_NAME
    environment:
      EULA: "TRUE"
      ALLOW_LIST_USERS: $MINECRAFT_ALLOW_LIST
      OPS: $MINECRAFT_OPS
      MEMBERS: $MINECRAFT_MEMBERS
      ONLINE_MODE: true
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /store/minecraft:/data
#Using local storage instead of remote for performance reasons
#    - type: volume
#      source: minecraft
#      target: /data
#      volume:
#        nocopy: true
    networks:
      - apps
    ports:
      - 19132:19132/udp
    restart: unless-stopped

networks:
  apps:
    name: apps
    ipam:
      driver: default
      config:
        - subnet: $APPS_SUBNET
          gateway: $APPS_GW