version: "3.2"
services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:latest
    container_name: $ZABBIX_PROXY_SERVICE_NAME
    environment:
    - ZBX_SERVER_HOST=$ZABBIX_SERVER_SERVICE_NAME
    - ZBX_HOSTNAME=$ZABBIX_PROXY_SERVICE_NAME
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    networks:
      - apps
    ports:
    - 10456:10051
    restart: unless-stopped

networks:
  apps:
    name: apps
    ipam:
      driver: default
      config:
        - subnet: $APPS_SUBNET
          gateway: $APPS_GW