version: "3.2"
services:
  pihole:
    container_name: $PIHOLE_SERVICE_NAME
    image: pihole/pihole:latest
# For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5380:80"
#      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    environment:
      - TZ=$TZ
      - WEBPASSWORD=$PIHOLE_WEBPASSWORD
#    labels:
#    - traefik.enable=true 
#    - traefik.http.routers.$PIHOLE_SERVICE_NAME.rule=Host(`$PIHOLE_ADDR_NAME.$DOMAIN`)
#    - traefik.http.routers.$PIHOLE_SERVICE_NAME.entrypoints=web
#    - traefik.http.routers.$PIHOLE_SERVICE_NAME-https.rule=Host(`$PIHOLE_ADDR_NAME.$DOMAIN`)
#    - traefik.http.routers.$PIHOLE_SERVICE_NAME-https.entrypoints=webs
#    - traefik.http.routers.$PIHOLE_SERVICE_NAME-https.middlewares=$AUTHELIA_SERVICE_NAME@docker
#    - traefik.http.routers.$PIHOLE_SERVICE_NAME-https.middlewares=$PIHOLE_SERVICE_NAME-prefix
#    - traefik.http.routers.$PIHOLE_SERVICE_NAME-https.tls=true
#    - traefik.http.routers.$PIHOLE_SERVICE_NAME-https.service=$PIHOLE_SERVICE_NAME
#    - traefik.http.routers.$PIHOLE_SERVICE_NAME-https.tls.certresolver=$CERTRESOLVER
#    - traefik.http.services.$PIHOLE_SERVICE_NAME.loadbalancer.server.port=80
#    - traefik.http.middlewares.$PIHOLE_SERVICE_NAME-prefix.addprefix.prefix=/admin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - type: volume
        source: pihole
        target: /etc/pihole
        volume:
          nocopy: true
      
      - type: volume
        source: pihole-dnsmasq
        target: /etc/dnsmasq.d
        volume:
          nocopy: true
#   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#    cap_add:
#      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: always
    networks:
      - controllers

networks:
  controllers:
    name: controllers
    ipam:
      driver: default
      config:
        - subnet: $CONTROLLERS_SUBNET
          gateway: $CONTROLLERS_GW

volumes:
  pihole:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/pihole/"

  pihole-dnsmasq:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/pihole-dnsmasq.d/"