- name: Update package cache
  apt:
    update_cache: yes

- name: Ensure Node.js and npm are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nodejs
    - npm

- name: Copy hostsfile
  copy:
    src: /etc/hosts
    dest: /etc/hosts

- name: Copy application folder
  copy:
    src: app/frontend/
    dest: "{{ node_app_path }}"
    mode: "0755"

- name: Install Node.js dependencies
  npm:
    path: "{{ node_app_path }}"
    state: latest

- name: Set environment variables
  set_fact:
    BACKEND_URL: "{{ backend_url }}"
    PORT: "{{ app_port }}"

- name: Create systemd service file for the Node.js application
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Start and enable the Node.js application service
  systemd:
    name: app
    state: started
    enabled: yes
