version: "3.2"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    environment:
      - PUID=$PUID
      - PGID=$PGID
    labels:
    - traefik.enable=true 
    - traefik.http.routers.dashy.rule=Host(`$DOMAIN`, `dash.$DOMAIN`, `www.$DOMAIN`)
    - traefik.http.routers.dashy.entrypoints=web
    - traefik.http.routers.dashy-https.rule=Host(`$DOMAIN`, `dash.$DOMAIN`, `www.$DOMAIN`)
    - traefik.http.routers.dashy-https.entrypoints=webs
    - traefik.http.routers.dashy-https.middlewares=authelia@docker
    - traefik.http.routers.dashy-https.middlewares=dashy-apexredirect@docker
    - traefik.http.routers.dashy-https.tls=true
    - traefik.http.routers.dashy-https.service=dashy
    - traefik.http.routers.dashy-https.tls.certresolver=$CERTRESOLVER
    - traefik.http.middlewares.dashy-apexredirect.redirectRegex.regex=^https:\/\/(?:www\.)?$DOMAIN/(.*)
    - traefik.http.middlewares.dashy-apexredirect.redirectRegex.replacement=https://dash.$DOMAIN/$${1}
    - traefik.http.middlewares.dashy-apexredirect.redirectRegex.permanent=true
    - traefik.http.services.dashy.loadbalancer.server.port=80
    volumes:
      - /mnt/docker/ymls/dashy-config.yml:/app/public/conf.yml
    restart: unless-stopped
    networks:
      - internalapps 

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=$PUID
      - PGID=$PGID
    labels:
    - traefik.enable=true 
    - traefik.http.routers.heimdall.rule=Host(`entertainment.$DOMAIN`)
    - traefik.http.routers.heimdall.entrypoints=web
    - traefik.http.routers.heimdall-https.rule=Host(`entertainment.$DOMAIN`)
    - traefik.http.routers.heimdall-https.entrypoints=webs
    - traefik.http.routers.heimdall-https.middlewares=authelia@docker
    - traefik.http.routers.heimdall-https.tls=true
    - traefik.http.routers.heimdall-https.service=heimdall
    - traefik.http.routers.heimdall-https.tls.certresolver=$CERTRESOLVER
    - traefik.http.services.heimdall.loadbalancer.server.port=443
    - traefik.http.services.heimdall.loadbalancer.server.scheme=https
    volumes:
      - type: volume
        source: heimdall
        target: /config
        volume:
          nocopy: true
    restart: unless-stopped
    networks:
      - internalapps 

  mysql:
    image: mariadb:latest
    container_name: mysql
    labels:
      - com.centurylinklabs.watchtower.monitor-only="true"
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql
        volume:
          nocopy: true  
    networks:
      - internalapps
    restart: unless-stopped     

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    labels:
    - traefik.enable=true 
    - traefik.http.routers.cloudbeaver.rule=Host(`sql.$DOMAIN`)
    - traefik.http.routers.cloudbeaver.entrypoints=web
    - traefik.http.routers.cloudbeaver-https.rule=Host(`sql.$DOMAIN`)
    - traefik.http.routers.cloudbeaver-https.entrypoints=webs
    - traefik.http.routers.cloudbeaver-https.middlewares=authelia@docker
    - traefik.http.routers.cloudbeaver-https.tls=true
    - traefik.http.routers.cloudbeaver-https.service=cloudbeaver
    - traefik.http.routers.cloudbeaver-https.tls.certresolver=$CERTRESOLVER
    - traefik.http.services.cloudbeaver.loadbalancer.server.port=8978
    volumes:
      - type: volume
        source: cloudbeaver
        target: /opt/cloudbeaver/workspace 
        volume:
          nocopy: true  
    restart: unless-stopped
    networks:
      - internalapps

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_HOSTNAME=$MYSQL_HOSTNAME
      - GUACD_HOSTNAME=$GUACD_HOSTNAME
    labels:
      - traefik.enable=true 
      - traefik.http.routers.guacamole.rule=Host(`remote.$DOMAIN`)
      - traefik.http.routers.guacamole.entrypoints=web
      - traefik.http.routers.guacamole-https.rule=Host(`remote.$DOMAIN`)
      - traefik.http.routers.guacamole-https.entrypoints=webs
      - traefik.http.routers.guacamole-https.middlewares=guacamole-prefix
      - traefik.http.routers.guacamole-https.tls=true
      - traefik.http.routers.guacamole-https.service=guacamole
      - traefik.http.routers.guacamole-https.tls.certresolver=$CERTRESOLVER
      - traefik.http.services.guacamole.loadbalancer.server.port=8080
      - traefik.http.middlewares.guacamole-prefix.addprefix.prefix=/guacamole
    networks:
        - internalapps
    restart: unless-stopped

  guacamole-daemon:
    image: guacamole/guacd
    container_name: guacamole-daemon
    networks:
        - internalapps
    restart: unless-stopped

  shlink-daemon:
    image: shlinkio/shlink:stable
    container_name: shlink-server
    environment:
    - DEFAULT_DOMAIN=$DEFAULT_DOMAIN
    - IS_HTTPS_ENABLED=true
    - GEOLITE_LICENSE_KEY=$GEOLITE_LICENSE_KEY
    - DB_DRIVER=$DB_DRIVER
    - DB_USER=$DB_USER
    - DB_PASSWORD=$DB_PASSWORD
    - DB_HOST=$DB_HOST
    labels:
      - traefik.enable=true 
      - traefik.http.routers.shlinkserver.rule=Host(`l.$DOMAIN_FORMAL`)
      - traefik.http.routers.shlinkserver.entrypoints=web
      - traefik.http.routers.shlinkserver-https.rule=Host(`l.$DOMAIN_FORMAL`)
      - traefik.http.routers.shlinkserver-https.entrypoints=webs
      - traefik.http.routers.shlinkserver-https.tls=true
      - traefik.http.routers.shlinkserver-https.service=shlinkserver
      - traefik.http.routers.shlinkserver-https.tls.certresolver=$CERTRESOLVER
      - traefik.http.services.shlinkserver.loadbalancer.server.port=8080
    restart: unless-stopped
    networks:
      - internalapps    
    
  shlink-web-client:
    image: shlinkio/shlink-web-client
    container_name: shlink-web
    environment:
    - SHLINK_SERVER_URL=https://$SHLINK_DEFAULT_DOMAIN
    - SHLINK_SERVER_API_KEY=$SHLINK_SERVER_API_KEY
    labels:
      - traefik.enable=true 
      - traefik.http.routers.shlink.rule=Host(`link.$DOMAIN`)
      - traefik.http.routers.shlink.entrypoints=web
      - traefik.http.routers.shlink-https.rule=Host(`link.$DOMAIN`)
      - traefik.http.routers.shlink-https.entrypoints=webs
      - traefik.http.routers.shlink-https.middlewares=authelia@docker
      - traefik.http.routers.shlink-https.tls=true
      - traefik.http.routers.shlink-https.service=shlink
      - traefik.http.routers.shlink-https.tls.certresolver=$CERTRESOLVER
      - traefik.http.services.shlink.loadbalancer.server.port=80
    volumes:
      - type: volume
        source: shlink
        target: /usr/share/nginx/html/conf.d/
        volume:
          nocopy: true  
    restart: unless-stopped
    networks:
      - internalapps

  littlelink-server:
    image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    environment:
      - META_TITLE=Network Security & Cloud Engineer | Ronald Rengifo
      - META_DESCRIPTION=Network Security & Cloud Engineer
      - META_AUTHOR=Ronald Rengifo
      - LANG=en
      - META_INDEX_STATUS=all
      - OG_SITE_NAME=Ronald Rengifo
      - OG_TITLE=Ronald Rengifo
#      - OG_DESCRIPTION=Ronald Rengifo
#      - OG_URL=https://
      - OG_IMAGE=https://avatars.githubusercontent.com/u/64389538
      - OG_IMAGE_WIDTH=260
      - OG_IMAGE_HEIGHT=260
#     - GA_TRACKING_ID=G-XXXXXXXXXX
      - THEME=Dark
      - FAVICON_URL=https://avatars.githubusercontent.com/u/64389538
      - AVATAR_URL=https://avatars.githubusercontent.com/u/64389538
      - AVATAR_2X_URL=https://avatars.githubusercontent.com/u/64389538
      - AVATAR_ALT=Ronald Rengifo Profile Pic
      - NAME=Ronald Rengifo B
      - BIO=🖥️ Over 10 years navigating the world of Linux Servers and networks ☁️ Now embarking on a Cloud Expedition & Diving into Penetration Testing | SRE - Network Security & Cloud Operations | 🌟 AWS Certified Solutions Architect
      # use ENV variable names for order, listed buttons will be boosted to the top
      - BUTTON_ORDER=CV,LINKED_IN,GITHUB
      - CUSTOM_BUTTON_TEXT=CV - Resume
      - CUSTOM_BUTTON_URL=https://l.$DOMAIN_FORMAL/cv
      - CUSTOM_BUTTON_COLOR=#000000
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff
      - CUSTOM_BUTTON_ALT_TEXT=My Resume
      - CUSTOM_BUTTON_NAME=CV
      - CUSTOM_BUTTON_ICON=fas file-alt
      - LINKED_IN=https://l.$DOMAIN_FORMAL/linkedin
      - GITHUB=https://l.$DOMAIN_FORMAL/github
      - EMAIL=hello@$DOMAIN_FORMAL
      - FOOTER=Ronald Rengifo © 2023
    labels:
      - traefik.enable=true 
      - traefik.http.routers.littlelink.rule=Host(`$DOMAIN_FORMAL`, `www.$DOMAIN_FORMAL`, `hello.$DOMAIN_FORMAL`)
      - traefik.http.routers.littlelink.entrypoints=web
      - traefik.http.routers.littlelink-https.rule=Host(`$DOMAIN_FORMAL`, `www.$DOMAIN_FORMAL`, `hello.$DOMAIN_FORMAL`)
      - traefik.http.routers.littlelink-https.entrypoints=webs
      - traefik.http.routers.littlelink-https.middlewares=ll-apexredirect@docker
      - traefik.http.routers.littlelink-https.tls=true
      - traefik.http.routers.littlelink-https.tls.certresolver=$CERTRESOLVER
      - traefik.http.routers.littlelink-https.service=littlelink
      - traefik.http.middlewares.ll-apexredirect.redirectRegex.regex=^https:\/\/(?:www\.)?$DOMAIN_FORMAL/(.*)
      - traefik.http.middlewares.ll-apexredirect.redirectRegex.replacement=https://hello.$DOMAIN_FORMAL/$${1}
      - traefik.http.middlewares.llapexredirect.redirectRegex.permanent=true

      - traefik.http.services.littlelink.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - internalapps
    security_opt:
      - no-new-privileges:true

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WEBUI_PORT=7070
    volumes:
      - /mnt/download/p2p:/downloads
      - type: volume
        source: qbittorrent
        target: /config
        volume:
          nocopy: true
    ports:
      - 6881:6881
      - 6881:6881/udp
    labels:
      - traefik.enable=true 
      - traefik.http.routers.qbittorrent.rule=Host(`torrent.$DOMAIN`)
      - traefik.http.routers.qbittorrent.entrypoints=web
      - traefik.http.routers.qbittorrent-https.rule=Host(`torrent.$DOMAIN`)
      - traefik.http.routers.qbittorrent-https.entrypoints=webs
#check connectivity with external apps
#      - traefik.http.routers.qbittorrent-https.middlewares=authelia@docker 
      - traefik.http.routers.qbittorrent-https.tls=true
      - traefik.http.routers.qbittorrent-https.service=qbittorrent
      - traefik.http.routers.qbittorrent-https.tls.certresolver=$CERTRESOLVER
      - traefik.http.services.qbittorrent.loadbalancer.server.port=7070
    networks:
      - apps
      - internalapps  
    restart: unless-stopped

  privatebin:
    image: privatebin/nginx-fpm-alpine:latest
    container_name: privatebin
    environment:
      - TZ=$TZ
    volumes:
      - /mnt/docker/ymls/privatebin.php:/srv/cfg/conf.php:ro
      - type: volume
        source: privatebin-data
        target: /srv/data
        volume: 
          nocopy: true
    labels:
      - traefik.enable=true 
      - traefik.http.routers.privatebin.rule=Host(`bin.$DOMAIN`)
      - traefik.http.routers.privatebin.entrypoints=web
      - traefik.http.routers.privatebin-https.rule=Host(`bin.$DOMAIN`)
      - traefik.http.routers.privatebin-https.entrypoints=webs
      - traefik.http.routers.privatebin-https.tls=true
      - traefik.http.routers.privatebin-https.service=privatebin
      - traefik.http.routers.privatebin-https.tls.certresolver=$CERTRESOLVER
      - traefik.http.services.privatebin.loadbalancer.server.port=8080
    networks:
      - internalapps  
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - /mnt/batocera:/mnt/batocera
      - type: volume
        source: syncthing-data
        target: /config
        volume: 
          nocopy: true
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      - traefik.enable=true 
      - traefik.http.routers.syncthing.rule=Host(`sync.$DOMAIN`)
      - traefik.http.routers.syncthing.entrypoints=web
      - traefik.http.routers.syncthing-https.rule=Host(`sync.$DOMAIN`)
      - traefik.http.routers.syncthing-https.entrypoints=webs
      - traefik.http.routers.syncthing-https.middlewares=authelia@docker
      - traefik.http.routers.syncthing-https.tls=true
      - traefik.http.routers.syncthing-https.service=syncthing
      - traefik.http.routers.syncthing-https.tls.certresolver=$CERTRESOLVER
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
    networks:
      - apps
      - internalapps  
    restart: unless-stopped

networks:
  internalapps:
    name: internalapps
    internal: true
    ipam:
      driver: default
      config:
        - subnet: $INTERNALAPPS_SUBNET
          gateway: $INTERNALAPPS_GW
  apps:
    name: apps
    ipam:
      driver: default
      config:
        - subnet: $APPS_SUBNET
          gateway: $APPS_GW

volumes:
  syncthing-data:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/syncthing/"

  heimdall:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/heimdall/"

  shlink:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/shlink/"

  mysql:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/mysql/"

  cloudbeaver:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/cloudbeaver/"

  privatebin-data:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/privatebin"

  qbittorrent:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/qbittorrent"