version: "3.2"
services:
  jenkins:
#pending change to custom ansible-jenkins image
    image: jenkins/jenkins 
    container_name: $JENKINS_SERVICE_NAME
#    ports:
#      - 8888:8080
    labels:
      - traefik.enable=true 
      - traefik.http.routers.$JENKINS_SERVICE_NAME.rule=Host(`$JENKINS_ADDR_NAME.$DOMAIN`)
      - traefik.http.routers.$JENKINS_SERVICE_NAME.entrypoints=web
      - traefik.http.routers.$JENKINS_SERVICE_NAME-https.rule=Host(`$JENKINS_ADDR_NAME.$DOMAIN`)
      - traefik.http.routers.$JENKINS_SERVICE_NAME-https.entrypoints=webs
      - traefik.http.routers.$JENKINS_SERVICE_NAME-https.middlewares=$AUTHELIA_SERVICE_NAME@docker
      - traefik.http.routers.$JENKINS_SERVICE_NAME-https.tls=true
      - traefik.http.routers.$JENKINS_SERVICE_NAME-https.service=$JENKINS_SERVICE_NAME
      - traefik.http.routers.$JENKINS_SERVICE_NAME-https.tls.certresolver=$CERTRESOLVER
      - traefik.http.services.$JENKINS_SERVICE_NAME.loadbalancer.server.port=8080
    volumes:
      - type: volume
        source: jenkins
        target: /var/jenkins_home
        volume:
          nocopy: true  
    restart: unless-stopped
    networks:
      - internalapps

networks:
  internalapps:
    name: internalapps
    internal: true
    ipam:
      driver: default
      config:
        - subnet: $INTERNALAPPS_SUBNET
          gateway: $INTERNALAPPS_GW

volumes:
  jenkins:
    driver_opts:
      type: "nfs4"
      o: "addr=$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/jenkins/"