version: "3.2"
services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: $PORTAINER_SERVICE_NAME
    labels:
    - traefik.enable=true 
    - traefik.http.routers.$PORTAINER_SERVICE_NAME.rule=Host(`$PORTAINER_SERVICE_NAME.$DOMAIN`)
    - traefik.http.routers.$PORTAINER_SERVICE_NAME.entrypoints=http
    - traefik.http.routers.$PORTAINER_SERVICE_NAME.middlewares=https-redirect
    - traefik.http.routers.$PORTAINER_SERVICE_NAME-https.rule=Host(`$PORTAINER_SERVICE_NAME.$DOMAIN`)
    - traefik.http.routers.$PORTAINER_SERVICE_NAME-https.entrypoints=https
    - traefik.http.routers.$PORTAINER_SERVICE_NAME-https.tls=true
    - traefik.http.routers.$PORTAINER_SERVICE_NAME-https.service=$PORTAINER_SERVICE_NAME
    - traefik.http.routers.$PORTAINER_SERVICE_NAME-https.tls.certresolver=$CERTRESOLVER
    - traefik.http.services.$PORTAINER_SERVICE_NAME.loadbalancer.server.port=9443
    - traefik.http.services.$PORTAINER_SERVICE_NAME.loadbalancer.server.scheme=https
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - type: volume
        source: portainer
        target: /data
        volume:
          nocopy: true  
    restart: unless-stopped
    networks:
      - controllers

networks:  
  controllers:
    name: controllers
    ipam:
      driver: default
      config:
        - subnet: $CONTROLLERS_SUBNET
          gateway: $CONTROLLERS_GW

volumes:
  portainer:
    driver_opts:
      type: "nfs4"
      o: "$NAS_ADDR,$NAS_MOUNT_PARAMS"
      device: "$NAS_PATH/portainer/"    